package com.ktb10.kgb.guidebook.entity;

import java.util.Arrays;
import java.util.List;

/** 행정안전부 2026-08-31 행정구역 기준의 2단계 시군구입니다. */
public enum AdministrativeDistrict {
    REGION_11110(AdministrativeProvince.SEOUL, "종로구"),
    REGION_11140(AdministrativeProvince.SEOUL, "중구"),
    REGION_11170(AdministrativeProvince.SEOUL, "용산구"),
    REGION_11200(AdministrativeProvince.SEOUL, "성동구"),
    REGION_11215(AdministrativeProvince.SEOUL, "광진구"),
    REGION_11230(AdministrativeProvince.SEOUL, "동대문구"),
    REGION_11260(AdministrativeProvince.SEOUL, "중랑구"),
    REGION_11290(AdministrativeProvince.SEOUL, "성북구"),
    REGION_11305(AdministrativeProvince.SEOUL, "강북구"),
    REGION_11320(AdministrativeProvince.SEOUL, "도봉구"),
    REGION_11350(AdministrativeProvince.SEOUL, "노원구"),
    REGION_11380(AdministrativeProvince.SEOUL, "은평구"),
    REGION_11410(AdministrativeProvince.SEOUL, "서대문구"),
    REGION_11440(AdministrativeProvince.SEOUL, "마포구"),
    REGION_11470(AdministrativeProvince.SEOUL, "양천구"),
    REGION_11500(AdministrativeProvince.SEOUL, "강서구"),
    REGION_11530(AdministrativeProvince.SEOUL, "구로구"),
    REGION_11545(AdministrativeProvince.SEOUL, "금천구"),
    REGION_11560(AdministrativeProvince.SEOUL, "영등포구"),
    REGION_11590(AdministrativeProvince.SEOUL, "동작구"),
    REGION_11620(AdministrativeProvince.SEOUL, "관악구"),
    REGION_11650(AdministrativeProvince.SEOUL, "서초구"),
    REGION_11680(AdministrativeProvince.SEOUL, "강남구"),
    REGION_11710(AdministrativeProvince.SEOUL, "송파구"),
    REGION_11740(AdministrativeProvince.SEOUL, "강동구"),
    REGION_12110(AdministrativeProvince.JEONNAM_GWANGJU, "목포시"),
    REGION_12130(AdministrativeProvince.JEONNAM_GWANGJU, "여수시"),
    REGION_12150(AdministrativeProvince.JEONNAM_GWANGJU, "순천시"),
    REGION_12170(AdministrativeProvince.JEONNAM_GWANGJU, "나주시"),
    REGION_12190(AdministrativeProvince.JEONNAM_GWANGJU, "광양시"),
    REGION_12210(AdministrativeProvince.JEONNAM_GWANGJU, "동구"),
    REGION_12240(AdministrativeProvince.JEONNAM_GWANGJU, "서구"),
    REGION_12270(AdministrativeProvince.JEONNAM_GWANGJU, "남구"),
    REGION_12300(AdministrativeProvince.JEONNAM_GWANGJU, "북구"),
    REGION_12330(AdministrativeProvince.JEONNAM_GWANGJU, "광산구"),
    REGION_12710(AdministrativeProvince.JEONNAM_GWANGJU, "담양군"),
    REGION_12720(AdministrativeProvince.JEONNAM_GWANGJU, "곡성군"),
    REGION_12730(AdministrativeProvince.JEONNAM_GWANGJU, "구례군"),
    REGION_12740(AdministrativeProvince.JEONNAM_GWANGJU, "고흥군"),
    REGION_12750(AdministrativeProvince.JEONNAM_GWANGJU, "보성군"),
    REGION_12760(AdministrativeProvince.JEONNAM_GWANGJU, "화순군"),
    REGION_12770(AdministrativeProvince.JEONNAM_GWANGJU, "장흥군"),
    REGION_12780(AdministrativeProvince.JEONNAM_GWANGJU, "강진군"),
    REGION_12790(AdministrativeProvince.JEONNAM_GWANGJU, "해남군"),
    REGION_12800(AdministrativeProvince.JEONNAM_GWANGJU, "영암군"),
    REGION_12810(AdministrativeProvince.JEONNAM_GWANGJU, "무안군"),
    REGION_12820(AdministrativeProvince.JEONNAM_GWANGJU, "함평군"),
    REGION_12830(AdministrativeProvince.JEONNAM_GWANGJU, "영광군"),
    REGION_12840(AdministrativeProvince.JEONNAM_GWANGJU, "장성군"),
    REGION_12850(AdministrativeProvince.JEONNAM_GWANGJU, "완도군"),
    REGION_12860(AdministrativeProvince.JEONNAM_GWANGJU, "진도군"),
    REGION_12870(AdministrativeProvince.JEONNAM_GWANGJU, "신안군"),
    REGION_26110(AdministrativeProvince.BUSAN, "중구"),
    REGION_26140(AdministrativeProvince.BUSAN, "서구"),
    REGION_26170(AdministrativeProvince.BUSAN, "동구"),
    REGION_26200(AdministrativeProvince.BUSAN, "영도구"),
    REGION_26230(AdministrativeProvince.BUSAN, "부산진구"),
    REGION_26260(AdministrativeProvince.BUSAN, "동래구"),
    REGION_26290(AdministrativeProvince.BUSAN, "남구"),
    REGION_26320(AdministrativeProvince.BUSAN, "북구"),
    REGION_26350(AdministrativeProvince.BUSAN, "해운대구"),
    REGION_26380(AdministrativeProvince.BUSAN, "사하구"),
    REGION_26410(AdministrativeProvince.BUSAN, "금정구"),
    REGION_26440(AdministrativeProvince.BUSAN, "강서구"),
    REGION_26470(AdministrativeProvince.BUSAN, "연제구"),
    REGION_26500(AdministrativeProvince.BUSAN, "수영구"),
    REGION_26530(AdministrativeProvince.BUSAN, "사상구"),
    REGION_26710(AdministrativeProvince.BUSAN, "기장군"),
    REGION_27110(AdministrativeProvince.DAEGU, "중구"),
    REGION_27140(AdministrativeProvince.DAEGU, "동구"),
    REGION_27170(AdministrativeProvince.DAEGU, "서구"),
    REGION_27200(AdministrativeProvince.DAEGU, "남구"),
    REGION_27230(AdministrativeProvince.DAEGU, "북구"),
    REGION_27260(AdministrativeProvince.DAEGU, "수성구"),
    REGION_27290(AdministrativeProvince.DAEGU, "달서구"),
    REGION_27710(AdministrativeProvince.DAEGU, "달성군"),
    REGION_27720(AdministrativeProvince.DAEGU, "군위군"),
    REGION_28125(AdministrativeProvince.INCHEON, "제물포구"),
    REGION_28155(AdministrativeProvince.INCHEON, "영종구"),
    REGION_28177(AdministrativeProvince.INCHEON, "미추홀구"),
    REGION_28185(AdministrativeProvince.INCHEON, "연수구"),
    REGION_28200(AdministrativeProvince.INCHEON, "남동구"),
    REGION_28237(AdministrativeProvince.INCHEON, "부평구"),
    REGION_28245(AdministrativeProvince.INCHEON, "계양구"),
    REGION_28275(AdministrativeProvince.INCHEON, "서해구"),
    REGION_28290(AdministrativeProvince.INCHEON, "검단구"),
    REGION_28710(AdministrativeProvince.INCHEON, "강화군"),
    REGION_28720(AdministrativeProvince.INCHEON, "옹진군"),
    REGION_30110(AdministrativeProvince.DAEJEON, "동구"),
    REGION_30140(AdministrativeProvince.DAEJEON, "중구"),
    REGION_30170(AdministrativeProvince.DAEJEON, "서구"),
    REGION_30200(AdministrativeProvince.DAEJEON, "유성구"),
    REGION_30230(AdministrativeProvince.DAEJEON, "대덕구"),
    REGION_31110(AdministrativeProvince.ULSAN, "중구"),
    REGION_31140(AdministrativeProvince.ULSAN, "남구"),
    REGION_31170(AdministrativeProvince.ULSAN, "동구"),
    REGION_31200(AdministrativeProvince.ULSAN, "북구"),
    REGION_31710(AdministrativeProvince.ULSAN, "울주군"),
    REGION_36110(AdministrativeProvince.SEJONG, "세종특별자치시"),
    REGION_41111(AdministrativeProvince.GYEONGGI, "수원시 장안구"),
    REGION_41113(AdministrativeProvince.GYEONGGI, "수원시 권선구"),
    REGION_41115(AdministrativeProvince.GYEONGGI, "수원시 팔달구"),
    REGION_41117(AdministrativeProvince.GYEONGGI, "수원시 영통구"),
    REGION_41131(AdministrativeProvince.GYEONGGI, "성남시 수정구"),
    REGION_41133(AdministrativeProvince.GYEONGGI, "성남시 중원구"),
    REGION_41135(AdministrativeProvince.GYEONGGI, "성남시 분당구"),
    REGION_41150(AdministrativeProvince.GYEONGGI, "의정부시"),
    REGION_41171(AdministrativeProvince.GYEONGGI, "안양시 만안구"),
    REGION_41173(AdministrativeProvince.GYEONGGI, "안양시 동안구"),
    REGION_41192(AdministrativeProvince.GYEONGGI, "부천시 원미구"),
    REGION_41194(AdministrativeProvince.GYEONGGI, "부천시 소사구"),
    REGION_41196(AdministrativeProvince.GYEONGGI, "부천시 오정구"),
    REGION_41210(AdministrativeProvince.GYEONGGI, "광명시"),
    REGION_41220(AdministrativeProvince.GYEONGGI, "평택시"),
    REGION_41250(AdministrativeProvince.GYEONGGI, "동두천시"),
    REGION_41271(AdministrativeProvince.GYEONGGI, "안산시 상록구"),
    REGION_41273(AdministrativeProvince.GYEONGGI, "안산시 단원구"),
    REGION_41281(AdministrativeProvince.GYEONGGI, "고양시 덕양구"),
    REGION_41285(AdministrativeProvince.GYEONGGI, "고양시 일산동구"),
    REGION_41287(AdministrativeProvince.GYEONGGI, "고양시 일산서구"),
    REGION_41290(AdministrativeProvince.GYEONGGI, "과천시"),
    REGION_41310(AdministrativeProvince.GYEONGGI, "구리시"),
    REGION_41360(AdministrativeProvince.GYEONGGI, "남양주시"),
    REGION_41370(AdministrativeProvince.GYEONGGI, "오산시"),
    REGION_41390(AdministrativeProvince.GYEONGGI, "시흥시"),
    REGION_41410(AdministrativeProvince.GYEONGGI, "군포시"),
    REGION_41430(AdministrativeProvince.GYEONGGI, "의왕시"),
    REGION_41450(AdministrativeProvince.GYEONGGI, "하남시"),
    REGION_41461(AdministrativeProvince.GYEONGGI, "용인시 처인구"),
    REGION_41463(AdministrativeProvince.GYEONGGI, "용인시 기흥구"),
    REGION_41465(AdministrativeProvince.GYEONGGI, "용인시 수지구"),
    REGION_41480(AdministrativeProvince.GYEONGGI, "파주시"),
    REGION_41500(AdministrativeProvince.GYEONGGI, "이천시"),
    REGION_41550(AdministrativeProvince.GYEONGGI, "안성시"),
    REGION_41570(AdministrativeProvince.GYEONGGI, "김포시"),
    REGION_41591(AdministrativeProvince.GYEONGGI, "화성시 만세구"),
    REGION_41593(AdministrativeProvince.GYEONGGI, "화성시 효행구"),
    REGION_41595(AdministrativeProvince.GYEONGGI, "화성시 병점구"),
    REGION_41597(AdministrativeProvince.GYEONGGI, "화성시 동탄구"),
    REGION_41610(AdministrativeProvince.GYEONGGI, "광주시"),
    REGION_41630(AdministrativeProvince.GYEONGGI, "양주시"),
    REGION_41650(AdministrativeProvince.GYEONGGI, "포천시"),
    REGION_41670(AdministrativeProvince.GYEONGGI, "여주시"),
    REGION_41800(AdministrativeProvince.GYEONGGI, "연천군"),
    REGION_41820(AdministrativeProvince.GYEONGGI, "가평군"),
    REGION_41830(AdministrativeProvince.GYEONGGI, "양평군"),
    REGION_43111(AdministrativeProvince.CHUNGBUK, "청주시 상당구"),
    REGION_43112(AdministrativeProvince.CHUNGBUK, "청주시 서원구"),
    REGION_43113(AdministrativeProvince.CHUNGBUK, "청주시 흥덕구"),
    REGION_43114(AdministrativeProvince.CHUNGBUK, "청주시 청원구"),
    REGION_43130(AdministrativeProvince.CHUNGBUK, "충주시"),
    REGION_43150(AdministrativeProvince.CHUNGBUK, "제천시"),
    REGION_43720(AdministrativeProvince.CHUNGBUK, "보은군"),
    REGION_43730(AdministrativeProvince.CHUNGBUK, "옥천군"),
    REGION_43740(AdministrativeProvince.CHUNGBUK, "영동군"),
    REGION_43745(AdministrativeProvince.CHUNGBUK, "증평군"),
    REGION_43750(AdministrativeProvince.CHUNGBUK, "진천군"),
    REGION_43760(AdministrativeProvince.CHUNGBUK, "괴산군"),
    REGION_43770(AdministrativeProvince.CHUNGBUK, "음성군"),
    REGION_43800(AdministrativeProvince.CHUNGBUK, "단양군"),
    REGION_44131(AdministrativeProvince.CHUNGNAM, "천안시 동남구"),
    REGION_44133(AdministrativeProvince.CHUNGNAM, "천안시 서북구"),
    REGION_44150(AdministrativeProvince.CHUNGNAM, "공주시"),
    REGION_44180(AdministrativeProvince.CHUNGNAM, "보령시"),
    REGION_44200(AdministrativeProvince.CHUNGNAM, "아산시"),
    REGION_44210(AdministrativeProvince.CHUNGNAM, "서산시"),
    REGION_44230(AdministrativeProvince.CHUNGNAM, "논산시"),
    REGION_44250(AdministrativeProvince.CHUNGNAM, "계룡시"),
    REGION_44270(AdministrativeProvince.CHUNGNAM, "당진시"),
    REGION_44710(AdministrativeProvince.CHUNGNAM, "금산군"),
    REGION_44760(AdministrativeProvince.CHUNGNAM, "부여군"),
    REGION_44770(AdministrativeProvince.CHUNGNAM, "서천군"),
    REGION_44790(AdministrativeProvince.CHUNGNAM, "청양군"),
    REGION_44800(AdministrativeProvince.CHUNGNAM, "홍성군"),
    REGION_44810(AdministrativeProvince.CHUNGNAM, "예산군"),
    REGION_44825(AdministrativeProvince.CHUNGNAM, "태안군"),
    REGION_47111(AdministrativeProvince.GYEONGBUK, "포항시 남구"),
    REGION_47113(AdministrativeProvince.GYEONGBUK, "포항시 북구"),
    REGION_47130(AdministrativeProvince.GYEONGBUK, "경주시"),
    REGION_47150(AdministrativeProvince.GYEONGBUK, "김천시"),
    REGION_47170(AdministrativeProvince.GYEONGBUK, "안동시"),
    REGION_47190(AdministrativeProvince.GYEONGBUK, "구미시"),
    REGION_47210(AdministrativeProvince.GYEONGBUK, "영주시"),
    REGION_47230(AdministrativeProvince.GYEONGBUK, "영천시"),
    REGION_47250(AdministrativeProvince.GYEONGBUK, "상주시"),
    REGION_47280(AdministrativeProvince.GYEONGBUK, "문경시"),
    REGION_47290(AdministrativeProvince.GYEONGBUK, "경산시"),
    REGION_47730(AdministrativeProvince.GYEONGBUK, "의성군"),
    REGION_47750(AdministrativeProvince.GYEONGBUK, "청송군"),
    REGION_47760(AdministrativeProvince.GYEONGBUK, "영양군"),
    REGION_47770(AdministrativeProvince.GYEONGBUK, "영덕군"),
    REGION_47820(AdministrativeProvince.GYEONGBUK, "청도군"),
    REGION_47830(AdministrativeProvince.GYEONGBUK, "고령군"),
    REGION_47840(AdministrativeProvince.GYEONGBUK, "성주군"),
    REGION_47850(AdministrativeProvince.GYEONGBUK, "칠곡군"),
    REGION_47900(AdministrativeProvince.GYEONGBUK, "예천군"),
    REGION_47920(AdministrativeProvince.GYEONGBUK, "봉화군"),
    REGION_47930(AdministrativeProvince.GYEONGBUK, "울진군"),
    REGION_47940(AdministrativeProvince.GYEONGBUK, "울릉군"),
    REGION_48121(AdministrativeProvince.GYEONGNAM, "창원시 의창구"),
    REGION_48123(AdministrativeProvince.GYEONGNAM, "창원시 성산구"),
    REGION_48125(AdministrativeProvince.GYEONGNAM, "창원시 마산합포구"),
    REGION_48127(AdministrativeProvince.GYEONGNAM, "창원시 마산회원구"),
    REGION_48129(AdministrativeProvince.GYEONGNAM, "창원시 진해구"),
    REGION_48170(AdministrativeProvince.GYEONGNAM, "진주시"),
    REGION_48220(AdministrativeProvince.GYEONGNAM, "통영시"),
    REGION_48240(AdministrativeProvince.GYEONGNAM, "사천시"),
    REGION_48250(AdministrativeProvince.GYEONGNAM, "김해시"),
    REGION_48270(AdministrativeProvince.GYEONGNAM, "밀양시"),
    REGION_48310(AdministrativeProvince.GYEONGNAM, "거제시"),
    REGION_48330(AdministrativeProvince.GYEONGNAM, "양산시"),
    REGION_48720(AdministrativeProvince.GYEONGNAM, "의령군"),
    REGION_48730(AdministrativeProvince.GYEONGNAM, "함안군"),
    REGION_48740(AdministrativeProvince.GYEONGNAM, "창녕군"),
    REGION_48820(AdministrativeProvince.GYEONGNAM, "고성군"),
    REGION_48840(AdministrativeProvince.GYEONGNAM, "남해군"),
    REGION_48850(AdministrativeProvince.GYEONGNAM, "하동군"),
    REGION_48860(AdministrativeProvince.GYEONGNAM, "산청군"),
    REGION_48870(AdministrativeProvince.GYEONGNAM, "함양군"),
    REGION_48880(AdministrativeProvince.GYEONGNAM, "거창군"),
    REGION_48890(AdministrativeProvince.GYEONGNAM, "합천군"),
    REGION_50110(AdministrativeProvince.JEJU, "제주시"),
    REGION_50130(AdministrativeProvince.JEJU, "서귀포시"),
    REGION_51110(AdministrativeProvince.GANGWON, "춘천시"),
    REGION_51130(AdministrativeProvince.GANGWON, "원주시"),
    REGION_51150(AdministrativeProvince.GANGWON, "강릉시"),
    REGION_51170(AdministrativeProvince.GANGWON, "동해시"),
    REGION_51190(AdministrativeProvince.GANGWON, "태백시"),
    REGION_51210(AdministrativeProvince.GANGWON, "속초시"),
    REGION_51230(AdministrativeProvince.GANGWON, "삼척시"),
    REGION_51720(AdministrativeProvince.GANGWON, "홍천군"),
    REGION_51730(AdministrativeProvince.GANGWON, "횡성군"),
    REGION_51750(AdministrativeProvince.GANGWON, "영월군"),
    REGION_51760(AdministrativeProvince.GANGWON, "평창군"),
    REGION_51770(AdministrativeProvince.GANGWON, "정선군"),
    REGION_51780(AdministrativeProvince.GANGWON, "철원군"),
    REGION_51790(AdministrativeProvince.GANGWON, "화천군"),
    REGION_51800(AdministrativeProvince.GANGWON, "양구군"),
    REGION_51810(AdministrativeProvince.GANGWON, "인제군"),
    REGION_51820(AdministrativeProvince.GANGWON, "고성군"),
    REGION_51830(AdministrativeProvince.GANGWON, "양양군"),
    REGION_52111(AdministrativeProvince.JEONBUK, "전주시 완산구"),
    REGION_52113(AdministrativeProvince.JEONBUK, "전주시 덕진구"),
    REGION_52130(AdministrativeProvince.JEONBUK, "군산시"),
    REGION_52140(AdministrativeProvince.JEONBUK, "익산시"),
    REGION_52180(AdministrativeProvince.JEONBUK, "정읍시"),
    REGION_52190(AdministrativeProvince.JEONBUK, "남원시"),
    REGION_52210(AdministrativeProvince.JEONBUK, "김제시"),
    REGION_52710(AdministrativeProvince.JEONBUK, "완주군"),
    REGION_52720(AdministrativeProvince.JEONBUK, "진안군"),
    REGION_52730(AdministrativeProvince.JEONBUK, "무주군"),
    REGION_52740(AdministrativeProvince.JEONBUK, "장수군"),
    REGION_52750(AdministrativeProvince.JEONBUK, "임실군"),
    REGION_52770(AdministrativeProvince.JEONBUK, "순창군"),
    REGION_52790(AdministrativeProvince.JEONBUK, "고창군"),
    REGION_52800(AdministrativeProvince.JEONBUK, "부안군");

    private final AdministrativeProvince province;
    private final String displayName;

    AdministrativeDistrict(
            AdministrativeProvince province,
            String displayName) {
        this.province = province;
        this.displayName = displayName;
    }

    public AdministrativeProvince province() {
        return province;
    }

    public String displayName() {
        return displayName;
    }

    /** 서비스의 2단계 선택값입니다. 일반 시 산하 구는 시 단위로 합칩니다. */
    public String serviceName() {
        int nestedDistrictSeparator = displayName.indexOf(' ');
        if (nestedDistrictSeparator < 0) {
            return displayName;
        }
        return displayName.substring(0, nestedDistrictSeparator);
    }

    public static AdministrativeDistrict fromDisplayName(
            AdministrativeProvince province,
            String displayName) {
        return Arrays.stream(values())
                .filter(district -> district.province == province)
                .filter(district -> district.serviceName().equals(displayName))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException(
                        "지원하지 않는 시도·시군구 조합입니다: "
                                + province.displayName() + " " + displayName));
    }

    public static List<AdministrativeDistrict> findAllByProvince(
            AdministrativeProvince province) {
        return Arrays.stream(values())
                .filter(district -> district.province == province)
                .toList();
    }

    public static List<String> findServiceNamesByProvince(
            AdministrativeProvince province) {
        return Arrays.stream(values())
                .filter(district -> district.province == province)
                .map(AdministrativeDistrict::serviceName)
                .distinct()
                .toList();
    }
}
